-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
----------------------------------------------------
-- WSL2 Clipboard Sync
-- vim.g.clipboard = {
--   name = "WslClipboard",
--   copy = {
--     ["+"] = { "clip.exe" },
--     ["*"] = { "clip.exe" },
--   },
--   paste = {
--     ["+"] = {
--       "/mnt/c/windows/system32/windowspowershell/v1.0///powershell.exe",
--       "-c",
--       '[console]::out.write($(get-clipboard -raw).tostring().replace("`r", ""))',
--     },
--     ["*"] = {
--       "/mnt/c/windows/system32/windowspowershell/v1.0///powershell.exe",
--       "-c",
--       '[console]::out.write($(get-clipboard -raw).tostring().replace("`r", ""))',
--     },
--   },
--   cache_enabled = false,
-- }
