# preload = ~/Pictures/wallpaper/拾yellow.jpg
preload = ~/Pictures/wallpaper/TimelineDark.jpg
# wallpaper = ,~/Pictures/wallpaper/拾yellow.jpg
wallpaper = ,~/Pictures/wallpaper/TimelineDark.jpg
ipc = off
splash = true
