# [colors]
# bg_trans = "#A5D9B7"
# ansi = [
#   "#dadac2",
#   "#c72a3c",
#   "#27850b",
#   "#a77b00",
#   "#1745d5",
#   "#8a4adf",
#   "#188a9e",
#   "#3a4238",
# ]
# background = "#252623"
# brights = [
#   "#c7c7af",
#   "#c72a3c",
#   "#27850b",
#   "#a77b00",
#   "#1745d5",
#   "#8a4adf",
#   "#188a9e",
#   "#252623",
# ]
# cursor_bg = "#27850b"
# cursor_border = "#27850b"
# cursor_fg = "#fff8f0"
# foreground = "#3a4238"
# scrollbar_thumb = "#c7c7af"
# selection_bg = "#a1a7a0"
# selection_fg = "#3a4238"
# split = "#838781"
# compose_cursor = "#df5926"
# visual_bell = "#e4e4cc"
#
# [colors.indexed]
#
# [colors.tab_bar]
# background = "#e4e4cc"
# inactive_tab_edge = "#dadac2"
#
# [colors.tab_bar.active_tab]
# bg_color = "#3a4238"
# fg_color = "#fafae0"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
#
# [colors.tab_bar.inactive_tab]
# bg_color = "#c7c7af"
# fg_color = "#5b5e5a"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
#
# [colors.tab_bar.inactive_tab_hover]
# bg_color = "#838781"
# fg_color = "#dadac2"
# intensity = "Normal"
# italic = true
# strikethrough = false
# underline = "None"
#
# [colors.tab_bar.new_tab]
# bg_color = "#a1a7a0"
# fg_color = "#dadac2"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
#
# [colors.tab_bar.new_tab_hover]
# bg_color = "#838781"
# fg_color = "#3a4238"
# intensity = "Normal"
# italic = false
# strikethrough = false
# underline = "None"
#
# [metadata]
# name = 'Bamboo'
# author = 'Riley Bruins'
# origin_url = "https://github.com/ribru17/bamboo.nvim"
# -------------------------------------------/
[colors]
ansi = [
  "#171f17",
  "#dc4f62",
  "#81af58",
  "#ceba49",
  "#409cdc",
  "#a09af8",
  "#68baae",
  "#ece1c0",
]
background = "#232923"
brights = [
  "#5a5e5a",
  "#dc4f62",
  "#81af58",
  "#ceba49",
  "#409cdc",
  "#a09af8",
  "#68baae",
  "#fff8f0",
]
cursor_bg = "#27850b"
cursor_border = "#fff8f0"
cursor_fg = "#0f0800"
foreground = "#ece1c0"
scrollbar_thumb = "#171f17"
selection_bg = "#5a5e5a"
selection_fg = "#ece1c0"
split = "#818781"
compose_cursor = "#ef9946"
visual_bell = "#363b35"

[colors.indexed]

[colors.tab_bar]
background = "#171f17"
inactive_tab_edge = "#383d37"

[colors.tab_bar.active_tab]
bg_color = "#ece1c0"
fg_color = "#101210"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#383d37"
fg_color = "#5a5e5a"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2d312c"
fg_color = "#818781"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#5a5e5a"
fg_color = "#ece1c0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#818781"
fg_color = "#ece1c0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
name = 'Bamboo'
author = 'Riley Bruins'
origin_url = "https://github.com/ribru17/bamboo.nvim"
